pipeline {
    agent any

    environment {
        APP_NAME = "my-next-test-app"
        BUILD_DIR = "next-app"
        DEPLOY_USER = "deploy"
        DEPLOY_HOST = "192.168.206.10"
        DEPLOY_PATH = "/var/www/html/${APP_NAME}"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master',
                // credentialsId: 'github-credentials',
                url: 'https://github.com/munirmahmud/my-next-test-app.git'
            }
        }

        stage('Install & Build') {
            steps {
                sh '''
                    npm install
                    npm run build
                '''
            }
        }

        stage('Prepare Artifact') {
            steps {
                sh '''
                    rm -rf ${BUILD_DIR}
                    mkdir ${BUILD_DIR}
                    cp -r .next public package.json ${BUILD_DIR}
                    pwd
                '''
            }
        }

        stage('Deploy to Production') {
            steps {
                sh """
                    ssh ${DEPLOY_USER}@${DEPLOY_HOST} 'rm -rf ${DEPLOY_PATH} && mkdir -p ${DEPLOY_PATH}'
                    scp -r ${BUILD_DIR}/* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}
                """
            }
        }

        stage('Restart PM2 on Production') {
            steps {
                sh """
                    ssh ${DEPLOY_USER}@${DEPLOY_HOST} '
                        cd ${DEPLOY_PATH} &&
                        pm2 delete ${APP_NAME} || true &&
                        pm2 start npm --name "${APP_NAME}" -- start &&
                        pm2 save
                    '
                """
            }
        }
    }
}
